//! Data directory resolution (see contract "数据目录").

use std::path::{Path, PathBuf};

pub const ENV_DATA_DIR: &str = "IMAGEPICKER_DATA_DIR";

/// On Android there is no platform data dir to ask for: the shell (Tauri plugin) passes the app's
/// private files dir as `CoreConfig::data_dir` / `ServerConfig::data_dir` (or sets
/// `IMAGEPICKER_DATA_DIR`); [`data_dir_resolvable`] lets callers fail fast otherwise.
///
/// Priority: explicit argument > `IMAGEPICKER_DATA_DIR` > platform default
/// (`%APPDATA%\imagePicker`, `~/Library/Application Support/imagePicker`, `$XDG_DATA_HOME/imagePicker`).
pub fn resolve_data_dir(explicit: Option<&Path>) -> PathBuf {
    if let Some(p) = explicit {
        return p.to_path_buf();
    }
    if let Some(p) = std::env::var_os(ENV_DATA_DIR).filter(|v| !v.is_empty()) {
        return PathBuf::from(p);
    }
    dirs::data_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join("imagePicker")
}

/// `false` only on Android when neither an explicit dir nor `IMAGEPICKER_DATA_DIR` is given.
pub fn data_dir_resolvable(explicit: Option<&Path>) -> bool {
    !cfg!(target_os = "android")
        || explicit.is_some()
        || std::env::var_os(ENV_DATA_DIR).is_some_and(|v| !v.is_empty())
}

#[derive(Debug, Clone)]
pub struct DataDirs {
    pub root: PathBuf,
    pub catalog: PathBuf,
    pub thumbs: PathBuf,
    pub previews: PathBuf,
    pub logs: PathBuf,
    /// Imported `.cube` LUTs (`/api/luts/import`).
    pub luts: PathBuf,
    /// AI mask PNGs generated by the worker.
    pub masks: PathBuf,
    /// Person geometry (skin/body masks + JSON) prepared by the worker for portrait retouching.
    pub beauty: PathBuf,
    /// Rendered thumbnails / previews of edited photos (keyed by edit hash).
    pub edited_thumbs: PathBuf,
    pub edited_previews: PathBuf,
    /// Generated patch assets (`<edits>/<photo_id>/<asset>.png`, M5).
    pub edits: PathBuf,
    /// Scratch space handed to the worker for generative requests.
    pub gen: PathBuf,
}

impl DataDirs {
    pub fn new(root: PathBuf) -> Self {
        Self {
            catalog: root.join("catalog.db"),
            thumbs: root.join("cache").join("thumbs"),
            previews: root.join("cache").join("previews"),
            logs: root.join("logs"),
            luts: root.join("luts"),
            masks: root.join("cache").join("masks"),
            beauty: root.join("cache").join("beauty"),
            edited_thumbs: root.join("cache").join("edited-thumbs"),
            edited_previews: root.join("cache").join("edited-previews"),
            edits: root.join("edits"),
            gen: root.join("cache").join("gen"),
            root,
        }
    }

    pub fn create(&self) -> std::io::Result<()> {
        std::fs::create_dir_all(&self.thumbs)?;
        std::fs::create_dir_all(&self.previews)?;
        std::fs::create_dir_all(&self.luts)?;
        std::fs::create_dir_all(&self.masks)?;
        std::fs::create_dir_all(&self.beauty)?;
        std::fs::create_dir_all(&self.edited_thumbs)?;
        std::fs::create_dir_all(&self.edited_previews)?;
        std::fs::create_dir_all(&self.edits)?;
        std::fs::create_dir_all(&self.gen)?;
        std::fs::create_dir_all(&self.logs)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn explicit_wins() {
        let p = resolve_data_dir(Some(Path::new("/x/y")));
        assert_eq!(p, PathBuf::from("/x/y"));
        let d = DataDirs::new(p);
        assert!(d.thumbs.ends_with("cache/thumbs") || d.thumbs.ends_with("cache\\thumbs"));
    }
}
