[package]
name = "ip-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "imagepicker"
path = "src/main.rs"

[dependencies]
ip-core.workspace = true
ip-server.workspace = true
anyhow.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true

[dev-dependencies]
ip-core = { workspace = true, features = ["testutil"] }
tempfile.workspace = true
image.workspace = true
