// Renders bench/REPORT.md from two result files.
//   node bench/report.mjs bench/results/baseline.json bench/results/after.json [frontend.json] > bench/REPORT.md
import { readFileSync, existsSync } from 'node:fs';

const [basePath, afterPath, frontPath] = process.argv.slice(2);
const A = JSON.parse(readFileSync(basePath, 'utf8'));
const B = JSON.parse(readFileSync(afterPath, 'utf8'));
const F = frontPath && existsSync(frontPath) ? JSON.parse(readFileSync(frontPath, 'utf8')) : null;

const fmt = (x) => (x === undefined || x === null ? 'n/a' : typeof x === 'number' ? (x >= 100 ? Math.round(x) : x.toFixed(1)) : x);
const ratio = (a, b) => (a && b ? `${(a / b).toFixed(1)}x` : '');
const out = [];
const p = (s = '') => out.push(s);
const ok = (v, target) => (v === undefined ? '' : v <= target ? 'PASS' : 'MISS');

p('# Performance report (M7)');
p();
p(`Generated by \`bench/report.mjs\` from \`${basePath.split(/[\\/]/).pop()}\` (before) and \`${afterPath.split(/[\\/]/).pop()}\` (after).`);
p(`Host: Windows 11, 24 threads, NVMe, release build, loopback HTTP. Times in ms unless noted; \`p50\` over ${A.quick ? 5 : 30} samples.`);
p('All data is synthetic (`imagepicker bench gen|seed`); no real photos.');
p('The machine was shared with other builds while measuring, so differences under ~20% are noise.');
p();
p('## PRD section 4 targets');
p();
p('| Target | PRD | Before | After | Status |');
p('|---|---|---|---|---|');
const cs = (r) => r.cold_start_ms?.catalog_20k?.p50;
p(`| Cold start to \`/api/health\` (existing 20k catalog) | < 2000 ms | ${fmt(cs(A))} | ${fmt(cs(B))} | ${ok(cs(B), 2000)} |`);
const ce = (r) => r.cold_start_ms?.empty_catalog?.p50;
p(`| Cold start, first run (empty catalog) | < 2000 ms | ${fmt(ce(A))} | ${fmt(ce(B))} | ${ok(ce(B), 2000)} |`);
const im = (r, k) => r.import?.ms?.[k];
p(`| Import ${B.import?.photos} x 12 MP JPEG: first screen (100 rows with metadata) | < 1000 ms | ${fmt(im(A, 'first_screen_meta'))} | ${fmt(im(B, 'first_screen_meta'))} | ${ok(im(B, 'first_screen_meta'), 1000)} |`);
p(`| Import: first 100 thumbnails | (informative) | ${fmt(im(A, 'thumbs_100'))} | ${fmt(im(B, 'thumbs_100'))} | |`);
p(`| Import: all thumbnails | < 10000 ms | ${fmt(im(A, 'thumbs_all'))} | ${fmt(im(B, 'thumbs_all'))} | ${ok(im(B, 'thumbs_all'), 10000)} |`);
if (F) {
  const fe = (side, k) => F[side]?.[k];
  p(`| Grid scroll, 20k photos, real server, 2500 px/s: p95 frame | <= 16.7 ms | ${fmt(fe('before', 'grid')?.p95)} | ${fmt(fe('after', 'grid')?.p95)} | ${ok(fe('after', 'grid')?.p95, 16.8)} |`);
  p(`| Grid scroll, dense (96 px, ungrouped) + 4x CPU throttle, 6000 px/s: p50 frame | (stress) | ${fmt(fe('before', 'dense_throttled_4x')?.['6000px/s']?.frame_ms?.p50)} | ${fmt(fe('after', 'dense_throttled_4x')?.['6000px/s']?.frame_ms?.p50)} | |`);
  p(`| Loupe next photo (key press to full preview painted) p95 | < 50 ms | ${fmt(fe('before', 'loupe')?.settled_ms?.p95)} | ${fmt(fe('after', 'loupe')?.settled_ms?.p95)} | ${ok(fe('after', 'loupe')?.settled_ms?.p95, 50)} |`);
}
const mem = (r) => r.memory_mb?.after_patch_20k?.priv;
p(`| Memory over a 20k session (private bytes, excluding models) | < 1536 MB | ${fmt(mem(A))} | ${fmt(mem(B))} | ${ok(mem(B), 1536)} |`);
const pull = (r) => r.query?.rows_20k_1session?.full_session_pull_ms?.p50;
p(`| Library scale: pull a whole 20k session (4 pages x 5000) | (informative) | ${fmt(pull(A))} | ${fmt(pull(B))} | |`);
p(`| Library scale: 100k rows / 5 sessions, first page | (informative) | ${fmt(A.query?.rows_100k_5sessions?.cases?.['default (taken_at) limit=500']?.p50)} | ${fmt(B.query?.rows_100k_5sessions?.cases?.['default (taken_at) limit=500']?.p50)} | |`);
p();

p('## Import (1000 x 12 MP JPEG, 24 threads)');
p();
p('| Mark | Before | After |');
p('|---|---|---|');
for (const k of ['import_call', 'first_rows_100', 'first_screen_meta', 'first_thumb', 'thumbs_100', 'thumbs_all', 'session_ready']) p(`| ${k} | ${fmt(im(A, k))} | ${fmt(im(B, k))} |`);
p(`| RSS after import (private MB) | ${fmt(A.import?.rss_after_import_mb?.priv)} | ${fmt(B.import?.rss_after_import_mb?.priv)} |`);
p();

p('## Cold start (ms, to first successful `GET /api/health`)');
p();
p('| Catalog | Before p50 | After p50 | After p95 |');
p('|---|---|---|---|');
for (const k of Object.keys(B.cold_start_ms ?? {})) p(`| ${k} | ${fmt(A.cold_start_ms?.[k]?.p50)} | ${fmt(B.cold_start_ms[k].p50)} | ${fmt(B.cold_start_ms[k].p95)} |`);
p();

for (const ds of Object.keys(B.query ?? {})) {
  const a = A.query?.[ds];
  const b = B.query[ds];
  p(`## \`GET /api/photos\` latency, ${ds} (ms, p50 / p95)`);
  p();
  p('| Case | Before p50 | After p50 | After p95 | Speed-up |');
  p('|---|---|---|---|---|');
  for (const c of Object.keys(b.cases)) p(`| ${c} | ${fmt(a?.cases?.[c]?.p50)} | ${fmt(b.cases[c].p50)} | ${fmt(b.cases[c].p95)} | ${ratio(a?.cases?.[c]?.p50, b.cases[c].p50)} |`);
  p();
  p('Cursor pagination depth (page of 500, sort=taken_at / name / ai; page N from the start):');
  p();
  p('| Sort | Page | Before | After |');
  p('|---|---|---|---|');
  for (const sort of Object.keys(b.cursor_depth_ms)) for (const pg of Object.keys(b.cursor_depth_ms[sort])) p(`| ${sort} | ${pg} | ${fmt(a?.cursor_depth_ms?.[sort]?.[pg])} | ${fmt(b.cursor_depth_ms[sort][pg])} |`);
  p();
  p(`Whole-session pull as the web does it (5000 per page): before ${fmt(a?.full_session_pull_ms?.p50)} ms, after ${fmt(b.full_session_pull_ms.p50)} ms. \`GET /api/sessions\`: before ${fmt(a?.sessions_list_ms?.p50)}, after ${fmt(b.sessions_list_ms.p50)}. \`/api/groups\`: ${fmt(a?.groups_ms?.p50)} -> ${fmt(b.groups_ms.p50)}. \`/api/people\`: ${fmt(a?.people_ms?.p50)} -> ${fmt(b.people_ms.p50)}.`);
  p();
}

p('## PATCH latency (20k session, ms)');
p();
p('| Request | Before p50 | After p50 | After p95 |');
p('|---|---|---|---|');
for (const k of Object.keys(B.patch_ws?.patch_ms ?? {})) p(`| ${k} | ${fmt(A.patch_ws?.patch_ms?.[k]?.p50)} | ${fmt(B.patch_ws.patch_ms[k].p50)} | ${fmt(B.patch_ws.patch_ms[k].p95)} |`);
p();
p('## WebSocket: PATCH to last `photos.updated` item received (ms)');
p();
p('| Items | Before | After | Frame size after (KB) |');
p('|---|---|---|---|');
for (const k of Object.keys(B.patch_ws?.ws ?? {})) p(`| ${k} | ${fmt(A.patch_ws?.ws?.[k]?.ms)} | ${fmt(B.patch_ws.ws[k].ms)} | ${fmt(B.patch_ws.ws[k].kb)} |`);
p();
p('Events are coalesced per 100 ms per type, so the floor is ~50 ms (half a tick on average).');
p();

p('## Thumbnail and preview latency (ms)');
p();
p('| Request | Before p50 | After p50 | After p95 |');
p('|---|---|---|---|');
for (const k of Object.keys(B.preview ?? {})) p(`| ${k} | ${fmt(A.preview?.[k]?.p50)} | ${fmt(B.preview[k].p50)} | ${fmt(B.preview[k].p95)} |`);
p();

p('## Memory over a 20k session (MB)');
p();
p('| Point | Before (private / working set / peak) | After (private / working set / peak) |');
p('|---|---|---|');
const m = (x) => (x ? `${x.priv} / ${x.ws} / ${x.peak}` : 'n/a');
for (const k of Object.keys(B.memory_mb ?? {})) p(`| ${k} | ${m(A.memory_mb?.[k])} | ${m(B.memory_mb[k])} |`);
p();

if (F) {
  p('## Frontend (Playwright + headless Chromium, REAL server, 20k photos, 1440x900)');
  p();
  p('`web/scripts/perf-real.mjs`: a requestAnimationFrame sampler while the grid scrolls at a fixed speed over the warm thumbnail cache; the loupe test presses ArrowRight 40 times (half relaxed, half quick). Headless Chromium rasterises in software, so absolute numbers are pessimistic.');
  p();
  p('| Metric | Before | After |');
  p('|---|---|---|');
  const row = (name, f) => p(`| ${name} | ${f('before') ?? 'n/a'} | ${f('after') ?? 'n/a'} |`);
  const fr = (o) => (o ? `${o.p50} / ${o.p95} / ${o.max}` : 'n/a');
  for (const sp of ['1500px/s', '2500px/s', '6000px/s']) row(`grid ${sp}: frame ms p50 / p95 / max`, (s) => fr(F[s]?.scroll_warm?.[sp]?.frame_ms));
  for (const sp of ['2500px/s', '6000px/s']) row(`dense grid, CPU 4x, ${sp}: frame ms p50 / p95 / max`, (s) => fr(F[s]?.dense_throttled_4x?.[sp]?.frame_ms));
  for (const sp of ['2500px/s', '6000px/s']) row(`dense grid, CPU 4x, ${sp}: frames over 33 ms`, (s) => `${F[s]?.dense_throttled_4x?.[sp]?.jank_frames_gt33ms} of ${F[s]?.dense_throttled_4x?.[sp]?.frames}`);
  row('jump to a random position: all visible thumbnails loaded (ms p50)', (s) => F[s]?.jump_settle_ms?.p50);
  row('loupe next: first pixels of the new photo (ms p50 / p95)', (s) => `${F[s]?.loupe?.first_pixels_ms?.p50} / ${F[s]?.loupe?.first_pixels_ms?.p95}`);
  row('loupe next: full preview painted (ms p50 / p95)', (s) => `${F[s]?.loupe?.settled_ms?.p50} / ${F[s]?.loupe?.settled_ms?.p95}`);
  row('loupe, key held (25 steps at 35 ms): last photo settled (ms)', (s) => (F[s]?.loupe_held_key != null ? Math.round(F[s].loupe_held_key) : null));
  row('first thumbnail visible after navigation (ms)', (s) => F[s]?.first_thumb_visible_ms);
  row('JS heap after loading 20k rows (MB)', (s) => F[s]?.js_heap_mb_after_load);
  row('console errors', (s) => F[s]?.console_errors?.length);
  p();
}
console.log(out.join('\n'));
